apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: aws-cli
  labels:
    app.kubernetes.io/version: "0.1"
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tags: cli
    displayName: "aws cli"
spec:
  description: >-
    This task performs operations on Amazon Web Services resources using aws.

  workspaces:
    - name: source
    - name: secrets
      mountPath: /tekton/home/.aws
  params:
    - name: SCRIPT
      description: The AWS script to run
      type: string
      default: "aws $@"
    - name: ARGS
      description: AWS cli arguments to be passed
      type: array
      default: ["help"]
  steps:
    - name: awscli
      image: amazon/aws-cli:latest
      script: "$(params.SCRIPT)"
      args:
        - "$(params.ARGS)"