apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: makisu
  labels:
    app.kubernetes.io/version: "0.1"
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tags: image-build
spec:
  description: >-
    This Task builds source into a container image using uber’s
    makisu tool.

    Makisu is a fast and flexible Docker image build tool designed for unprivileged
    containerized environments such as Mesos or Kubernetes. makisu uses a registry
    configuration which should be stored as a secret in Kubernetes.

  params:
  - name: CONTEXTPATH
    description: Path to the build context.
    default: /workspace
  - name: PUSH_REGISTRY
    description: Registry to push image to.
    default: index.docker.io
  - name: REGISTRY_SECRET
    description: Secret containing information about the used regsitry.
    default: docker-registry-config
  workspaces:
  - name: source
  resources:
    outputs:
    - name: image
      type: image
  steps:
  - name: build-and-push
    image: gcr.io/makisu-project/makisu:v0.1.10
    workingDir: $(workspaces.source.path)
    command:
    - /makisu-internal/makisu
    - build
    - --push=$(params.PUSH_REGISTRY)
    - --registry-config=/registry-config
    - --modifyfs=true
    - --tag=$(resources.outputs.image.url)
    - --registry-config=/registry-config/registry.yaml
    - $(params.CONTEXTPATH)
    env:
    - name: DOCKER_CONFIG
      value: /builder/home/.docker
    volumeMounts:
    - name: registry-config
      mountPath: /registry-config
  volumes:
  - name: registry-config
    secret:
      secretName: $(params.REGISTRY_SECRET)
