apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: kythe-go
  labels:
    app.kubernetes.io/version: "0.1"
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tags: annotations
    displayName: "kythe go"
spec:
  description: >-
    This task generates annotations for source code.

    The kythe-go Task runs the Kythe Go extractor for the given
    package, placing the resulting kzips in the output workspace.

  workspaces:
    - name: output
      description: Output directory for kzip output files.
  params:
    - name: package
      type: string
      description: Go package to analyze.
  steps:
    - name: analyze-packages
      image: gcr.io/kythe-public/golang-extractor:stable
      env:
        - name: OUTPUT
          value: $(workspaces.output.path)
      args: ["$(params.package)"]
