apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: replace-tokens
  labels:
    app.kubernetes.io/version: "0.1"
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tags: tokens
    dislayName: "replace tokens"
spec:
  description: >-
    This task can be used to replace tokens in a file.

    The supported file types are YAML and JSON.

  workspaces:
    - name: source
    - name: token
  params:
    - name: inputFilePath
      type: string
      description: The file path whose value needs to be replaced
  steps:
    - name: replace-tokens
      image: quay.io/vinamra2807/replace-tokens:latest
      workingDir: $(workspaces.source.path)
      args:
        - --inputfile=$(params.inputFilePath)
        - --tokensfile=$(workspaces.token.path)/tokens.json