apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: openshift-uninstall-run
spec:
  taskRef:
    name: openshift-uninstall
  workspaces:
    - name: install-dir
      persistentvolumeclaim:
        claimName: install-dir
